/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gro' at '3/15/16 8:24 AM' with Gradle 2.9
 *
 * @author gro, @date 3/15/16 8:24 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
